### ISSUE TITLE
合约内可以提供几个api吗

### ISSUE THREAD

**Issue by zhuxuyin** [gxchain/gxips#2]
1.根据用户的instace_id获取account_name
2.根据区块号可以获取区块hash

**Comment by zhuliting** [comment]
这2个接口在testnet已经支持了。
1. https://docs.gxchain.org/zh/contract/develop.html#get-account-name-by-id
2. https://docs.gxchain.org/zh/contract/develop.html#get-head-block-id

**Comment by zhuxuyin** [comment]
非常感谢,
