### ISSUE TITLE
收款码标准协议的提案（QRCode agreement of transfer）

### ISSUE THREAD

**Issue by chenluyong** [gxchain/gxips#4]
# 简介

该方案引用自[bip-0021.mediawiki](https://github.com/bitcoin/bips/blob/master/bip-0021.mediawiki)，用于进行币种支付的URI方案。

根据`URI RFC3986`标准，规定的URI的一般格式。使用`UTF-8`字符集来表示。

# 动机

此URI方案的目的是使用户只需单击网页上的链接或扫描二维码即可轻松进行付款。

# 详情

1. 根据币种，生成文本格式的收款参数字符串
2. 将文本字符串进行URLEncoder，编码格式选择UTF-8
3. URLEncoder后的文本生成收款二维码

# 示例

采用类URL 格式，各主流币种格式如下：

**币种名:地址?键=值&键=值&...&键=值**

地址：
```
gxchain:bepal
```

请求转入20.30 GXC:

```
gxchain:bepal?amount=20.3
```

请求转入 20.30 GXC 到标签为`BEPAL Pro S`地址上：

```
gxchain:bepal?label=BEPAL%20Pro%20S&amount=20.3&symbol=GXC
```

必须遵循正确的URI编码

# 扩展与标准

如果提案成立，接下里将利用子文档确定 `币种全称` 以及具体的 `参数字段`适应各式各样的币种以及定制化的展示需求，并以文档的形式确定为收款的标准。

**Comment by lanhaoxiang** [comment]
目前GXS Wallet支持的是 `gxchain://transfer?memo=12345&amount=20.3&to=account_name`，还可以加上`symbol`的支持

**Comment by chenluyong** [comment]
> 目前GXC Wallet支持的是 `gxchain://transfer?memo=12345&amount=20.3&to=account_name`，还可以加上`symbol`的支持
> 
> 作者上述提案个人觉得合理，可以按行业标准来实现

是的，继承已有的标准，从长远的发展来看是有必要的。
